export const mockData = [
  {
    city: "Warszawa",
    temperature: 18,
    description: "Part Cloudy",
    humidity: 75,
    windSpeed: 3.2,
    forecast: [
    { day: "Mon", temp: 17 },
    { day: "Tue", temp: 19 },
    { day: "Wed", temp: 21 },
    { day: "Thu", temp: 16 },
    { day: "Fri", temp: 18 },
  ]
},
{
    city: "Kraków",
    temperature: 20,
    description: "Sunny",
    humidity: 60,
    windSpeed: 2.5,
    forecast: [
      { day: "Mon", temp: 19 },
      { day: "Tue", temp: 21 },
      { day: "Wed", temp: 23 },
      { day: "Thu", temp: 20 },
      { day: "Fri", temp: 22 },
    ],
  },
{
    city: "Gdańsk",
    temperature: 20,
    description: "Sunny",
    humidity: 60,
    windSpeed: 2.5,
    forecast: [
      { day: "Mon", temp: 19 },
      { day: "Tue", temp: 21 },
      { day: "Wed", temp: 23 },
      { day: "Thu", temp: 20 },
      { day: "Fri", temp: 22 },
    ],
  },
  {
    city: "Wrocław",
    temperature: 16,
    description: "Rainy",
    humidity: 85,
    windSpeed: 4.1,
    forecast: [
      { day: "Mon", temp: 15 },
      { day: "Tue", temp: 17 },
      { day: "Wed", temp: 16 },
      { day: "Thu", temp: 14 },
      { day: "Fri", temp: 16 },
    ],
  },
{
    city: "Pisarzowa",
    temperature: 20,
    description: "Sunny",
    humidity: 60,
    windSpeed: 2.5,
    forecast: [
      { day: "Mon", temp: 19 },
      { day: "Tue", temp: 21 },
      { day: "Wed", temp: 23 },
      { day: "Thu", temp: 20 },
      { day: "Fri", temp: 22 },
    ],
  },
  {
    city: "Limanowa",
    temperature: 16,
    description: "Rainy",
    humidity: 85,
    windSpeed: 4.1,
    forecast: [
      { day: "Mon", temp: 15 },
      { day: "Tue", temp: 17 },
      { day: "Wed", temp: 16 },
      { day: "Thu", temp: 14 },
      { day: "Fri", temp: 16 },
    ],
  },
  {
    city: "Nowy Sącz",
    temperature: 16,
    description: "Rainy",
    humidity: 85,
    windSpeed: 4.1,
    forecast: [
      { day: "Mon", temp: 15 },
      { day: "Tue", temp: 17 },
      { day: "Wed", temp: 16 },
      { day: "Thu", temp: 14 },
      { day: "Fri", temp: 16 },
    ],
  },
  {
    city: "Zakopane",
    temperature: 18,
    description: "Part Cloudy",
    humidity: 75,
    windSpeed: 3.2,
    forecast: [
    { day: "Mon", temp: 17 },
    { day: "Tue", temp: 19 },
    { day: "Wed", temp: 21 },
    { day: "Thu", temp: 16 },
    { day: "Fri", temp: 18 },
  ]
},
{
    city: "Szczecin",
    temperature: 20,
    description: "Sunny",
    humidity: 60,
    windSpeed: 2.5,
    forecast: [
      { day: "Mon", temp: 19 },
      { day: "Tue", temp: 21 },
      { day: "Wed", temp: 23 },
      { day: "Thu", temp: 20 },
      { day: "Fri", temp: 22 },
    ],
  },
  {
    city: "Lublin",
    temperature: 16,
    description: "Rainy",
    humidity: 85,
    windSpeed: 4.1,
    forecast: [
      { day: "Mon", temp: 15 },
      { day: "Tue", temp: 17 },
      { day: "Wed", temp: 16 },
      { day: "Thu", temp: 14 },
      { day: "Fri", temp: 16 },
    ],
  }
]